Features/reviews in profile
BinaryStudioAcademy/bsa-2017-bebeep pull request #108
Opened 2017-08-31 19:13 UTC by lenchv

2017-08-31 20:03 UTC, TatsuUkraine requested changes

2017-08-31 20:03 UTC, TatsuUkraine commented on resources/assets/js/features/user/components/Profile/Reviews/GivenContainer.js
> +            <div style={{position: 'relative'}}>
avoid using inline styles

2017-08-31 20:03 UTC, TatsuUkraine commented on resources/assets/js/features/user/components/Profile/Reviews/GivenContainer.js
> +                <ReviewsListEmpty show={givenReviews.length <= 0 && !preloader} />
avoid using such statements, define variable or method that will describe this logic

2017-08-31 20:03 UTC, TatsuUkraine commented on resources/assets/js/features/user/components/Profile/Reviews/ReceivedContainer.js
> +            <div style={{position: 'relative'}}>
avoid using inline styles

2017-08-31 20:03 UTC, TatsuUkraine commented on resources/assets/js/features/user/components/Profile/Reviews/ReceivedContainer.js
> +                <ReviewsListEmpty show={receivedReviews.length <= 0 && !preloader} />
avoid using such statements in template, define variable or method that will return appropriate value

2017-08-31 20:03 UTC, TatsuUkraine commented on resources/assets/js/features/user/components/Profile/Reviews/Review.js
> +                                {(Number.isInteger(commentDate) && commentDate <= 7)
avoid using such statements in templates, define variable with appropriate value or method that will return needed value

2017-08-31 20:03 UTC, TatsuUkraine commented on resources/assets/js/features/user/components/Profile/Reviews/ReviewsList.js
> +                        user={users.byId[reviews.byId[id].user]}
create method that will know how to find user from given params

2017-08-31 20:03 UTC, TatsuUkraine commented on resources/assets/js/features/user/components/Profile/Reviews/ReviewsListEmpty.js
> +            <div style={displayStyle}>
avoid using inline styles

2017-08-31 20:03 UTC, TatsuUkraine commented on resources/assets/js/features/user/components/Profile/Reviews/GivenContainer.js
> +                <ReviewsListEmpty show={givenReviews.length <= 0 && !preloader} />
render ReviewsListEmpty or ReviewsList based on some criteria, not both in same time

2017-09-01 06:25 UTC, TatsuUkraine approved these changes

2017-09-01 06:40 UTC, sergey-ben approved these changes

2017-09-01 06:40 UTC, merged