Wish/autocomplete car
BinaryStudioAcademy/bsa-2017-bebeep pull request #123
Opened 2017-09-02 14:15 UTC by lenchv

2017-09-02 16:24 UTC, sergey-ben requested changes

2017-09-02 16:24 UTC, sergey-ben commented on routes/api.php
> +Route::get('v1/brands/{name?}/', ['as' => 'brands.byname', 'uses' => 'Api\Car\CarBrandController@brandsByName']);
лучше использовать существующий ендпоинт возвращающий коллекцию брендов - v1/car-brands. Для v1/car-brands стоит добавить обработку get параметра к примеру ?term=ford или ?name=nissan.
Тоже самое касается и ендпоинта моделей. Ну и конечно убрать для этих ендпоинтов миддлвеар аутентифицирующий пользователей

2017-09-02 16:24 UTC, sergey-ben commented on app/Http/Controllers/Api/Car/CarBrandController.php
> +        $brands = $this->carBrandService->getByName($name, 100);
лучше использовать константы

2017-09-02 16:24 UTC, sergey-ben commented on app/Services/CarBrandService.php
> +    public function getByName(string $name, int $limit = 10)
тут тоже лучше константы использовать

2017-09-02 16:25 UTC, TatsuUkraine requested changes

2017-09-02 16:25 UTC, TatsuUkraine commented on resources/assets/js/app/services/VehicleService.js
> +        return simpleRequest.get(`/api/v1/brands/${name}/`);
use get params (name or term or similar) to filter brand collection

2017-09-02 16:25 UTC, TatsuUkraine commented on resources/assets/js/app/services/VehicleService.js
> +            return simpleRequest.get(`/api/v1/models/${name}/`);
if brand wasn't selected from autocomplete, don't use autocomplete for models, also add filter Get param to filter collection by name

2017-09-02 16:25 UTC, TatsuUkraine commented on resources/assets/js/features/wizard-trip/components/StepThree.js
> +            .then((response) => this.setState({brands: _.unionBy(brands, response.data.data, 'id')}));
don't store all brands that was fetched, just enough to store last fetched collection

2017-09-02 16:25 UTC, TatsuUkraine commented on resources/assets/js/features/wizard-trip/components/StepThree.js
> +            .then((response) => this.setState({models: _.unionBy(models, response.data.data, 'id')}));
don't store all models that was fetched, just enough to store last fetched collection

2017-09-03 16:31 UTC, sergey-ben submitted a review, later dismissed

2017-09-03 16:59 UTC, TatsuUkraine requested changes

2017-09-03 16:59 UTC, TatsuUkraine commented on resources/assets/js/app/services/VehicleService.js
> +    fetchModel(name, brandId) {
this method is quite similar to getModelOptions, keep one of them, you can make 1 method that will provide request, and other method will use response to provide different data preparation

2017-09-03 16:59 UTC, TatsuUkraine commented on resources/assets/js/app/services/VehicleService.js
> +    fetchBrand(name) {
this method is quite similar to getBrandOptions, keep one of them, you can make 1 method that will provide request, and other method will use response to provide different data preparation

2017-09-03 16:59 UTC, TatsuUkraine commented on resources/assets/js/app/services/VehicleService.js
> +    fetchModel(name, brandId) {
if you name method fetch, than it should fetch data with any params, method name should reflect it's logic

2017-09-03 18:32 UTC, TatsuUkraine approved these changes

2017-09-04 06:20 UTC, merged