Trip animals and luggage size params
BinaryStudioAcademy/bsa-2017-bebeep pull request #128
Opened 2017-09-04 17:53 UTC by Rhincodon

2017-09-04 18:09 UTC, TatsuUkraine requested changes

2017-09-04 18:09 UTC, TatsuUkraine commented on resources/assets/js/features/trip/components/Forms/TripForm.js
> +                            <select defaultValue={this.props.trip ? this.props.trip.luggage_size : '2'} name="luggage_size" className="form-control" id="luggage_size">
define value in variable

2017-09-04 18:09 UTC, TatsuUkraine commented on resources/assets/js/features/trip/components/Forms/TripForm.js
> +                                    <input className="form-check-input" type="checkbox" id="is_animals_allowed" defaultChecked={this.props.trip ? this.props.trip.is_animals_allowed : false} />
define checked variable based on this check and use variable here instead of if statement

2017-09-04 18:29 UTC, TatsuUkraine approved these changes

2017-09-05 06:25 UTC, sergey-ben approved these changes

2017-09-05 06:25 UTC, merged