Improvement/auth session logic
BinaryStudioAcademy/bsa-2017-bebeep pull request #138
Opened 2017-09-08 06:15 UTC by ruig1992

[Store auth token in the global state](https://trello.com/c/5TaxtW1r)
[Hide functionality depending on the user role](https://trello.com/c/8wCSHVDb)

2017-09-08 14:39 UTC, ruig1992 commented
This awful ugly code is now changing in the hope of a better use.

2017-09-08 20:01 UTC, sergey-ben submitted a review, later dismissed

2017-09-08 22:26 UTC, ruig1992 commented
This code is much better.)

2017-09-11 07:21 UTC, TatsuUkraine requested changes

2017-09-11 07:21 UTC, TatsuUkraine commented on resources/assets/js/app/services/AuthService.js
> +            return _this.getFromState('token') || storage[tokenKeyName];
you should get token always from global state, localStorage should be used just as initial source of data. on app init you need get token from localStorage and put it in global state, on destroy session you need remove it from there and from global state, on initSession - put it in localStorage and global state. you can dispatch actions from this service to update state

2017-09-11 07:21 UTC, TatsuUkraine commented on resources/assets/js/app/services/AuthService.js
> +            return _this.getFromState('token') || storage[tokenKeyName];
in this case localStorage should be source of data only for page reload, it shouldn't be main source of data

2017-09-12 13:20 UTC, TatsuUkraine submitted a review, later dismissed

2017-09-12 20:37 UTC, TatsuUkraine approved these changes

2017-09-12 20:37 UTC, merged