Features/subscriptions manage
BinaryStudioAcademy/bsa-2017-bebeep pull request #143
Opened 2017-09-08 21:09 UTC by lenchv

2017-09-09 21:11 UTC, TatsuUkraine requested changes

2017-09-09 21:11 UTC, TatsuUkraine commented on resources/assets/js/features/subscriptions/components/Dropdowns/LuggageDropDown.js
> +class LuggageDropDown extends React.Component {
no need to create new component, we already have such dropdown component

2017-09-09 21:11 UTC, TatsuUkraine commented on resources/assets/js/app/services/SubscriptionService.js
> +        status: status ? 'activate' : 'deactivate'
send is_active with bool value instead of abstract status field with abstract activate/deactivate values

2017-09-09 21:11 UTC, TatsuUkraine commented on resources/assets/js/features/subscriptions/components/Dropdowns/AnimalsDropDown.js
> +class AnimalsDropDown extends React.Component {
same as for Luggage dropdown

2017-09-09 21:11 UTC, TatsuUkraine commented on resources/assets/js/features/subscriptions/components/Dropdowns/RatingDropDown.js
> +class RatingDropDown extends React.Component {
same as for Luggage dropdown

2017-09-10 12:32 UTC, TatsuUkraine requested changes

2017-09-10 12:32 UTC, TatsuUkraine commented on resources/assets/js/app/services/SubscriptionService.js
> +        status: !!status
property name should be equals to property that you going to update in your case as I understood it will be is_active, not status

2017-09-10 12:32 UTC, TatsuUkraine commented on resources/assets/js/features/subscriptions/components/SubscriptionItem.js
> +        }, 2000);
why you need 2sec timeout here?

2017-09-10 12:32 UTC, TatsuUkraine commented on resources/assets/js/features/subscriptions/components/SubscriptionItem.js
> +        }, 2000);
why you need 2sec timeout here?

2017-09-11 13:22 UTC, TatsuUkraine submitted a review, later dismissed

2017-09-11 18:47 UTC, TatsuUkraine commented
@lenchv resolve conflict

2017-09-11 18:50 UTC, sergey-ben submitted a review, later dismissed

2017-09-12 06:50 UTC, TatsuUkraine approved these changes

2017-09-12 06:51 UTC, merged