Feature/add start and end time for trip routes
BinaryStudioAcademy/bsa-2017-bebeep pull request #149
Opened 2017-09-10 22:32 UTC by ruig1992

[![trs](https://user-images.githubusercontent.com/12577743/30219063-9438ad58-94c3-11e7-8359-212ee6e46cea.png) Saving start and end times for each of the trip routes](https://trello.com/c/skJK6zgT)

2017-09-11 16:30 UTC, TatsuUkraine approved these changes

2017-09-11 16:49 UTC, ruig1992 commented
@TatsuUkraine  Conflicts resolved.

2017-09-11 17:45 UTC, TatsuUkraine requested changes

2017-09-11 17:45 UTC, TatsuUkraine commented on resources/assets/js/features/trip/components/Containers/CreateTripContainer.js
> +        this.tripEndTime = 0;
use local state

2017-09-11 17:45 UTC, TatsuUkraine commented on resources/assets/js/features/trip/components/Containers/CreateTripContainer.js
> +        this.waypointsDurations = [];
use local state

2017-09-11 17:45 UTC, TatsuUkraine commented on resources/assets/js/features/trip/components/Containers/EditTripContainer.js
> +        this.tripEndTime = 0;
use local state

2017-09-11 17:45 UTC, TatsuUkraine commented on resources/assets/js/features/trip/components/Containers/EditTripContainer.js
> +        this.waypointsDurations = [];
use local state

2017-09-11 18:47 UTC, TatsuUkraine commented
@ruig1992 resolve conflics

2017-09-11 19:01 UTC, ruig1992 commented
@TatsuUkraine  Conflicts resolved.

2017-09-12 06:52 UTC, sergey-ben approved these changes

2017-09-12 06:54 UTC, TatsuUkraine approved these changes

2017-09-12 07:26 UTC, merged