Features/trips list
BinaryStudioAcademy/bsa-2017-bebeep pull request #15
Opened 2017-08-11 17:38 UTC by mivashchuk

2017-08-11 19:38 UTC, TatsuUkraine requested changes

2017-08-11 19:38 UTC, TatsuUkraine commented on app/Managers/TripsManager.php
> +    public function userTrips(int $id)
only repository can work with DB

2017-08-11 19:38 UTC, TatsuUkraine commented on app/Http/Controllers/Api/Driver/TripListController.php
> +        }catch (UserNotHaveTrips $e){
if trips is empty return empty array, no need to fire error http code

2017-08-11 19:38 UTC, TatsuUkraine commented on app/Services/Contracts/TripsListService.php
> +    public function getUserTrips(int $userId);
use return types

2017-08-11 19:38 UTC, TatsuUkraine commented on app/Services/TripsListService.php
> +          throw new UserNotHaveTrips();
if user doesn't have trips return empty array

2017-08-11 19:38 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/actions.js
> +const url = 'http://localhost/api/v1/trips';
no need to specify full api url, it should starts with /

2017-08-11 19:38 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/actions.js
> +                console.log(response);
remove console.log

2017-08-11 19:38 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/actions.js
> +                console.log(error);
remove console.log

2017-08-11 19:38 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/reducer.js
> +    isOpen: false, // status of modal window
use local state for modal showing instead of global

2017-08-11 19:38 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/reducer.js
> +                item => (new Date(item.start_at)<new Date()))
use momentjs for date object manipulation, some browsers could have specific issues with date time parse from string

2017-08-11 19:38 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/actions.js
> +// const tripsData = [
remove commented code, or move it to file to load like deps if needed

2017-08-11 19:38 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/components/ListWithTripsItems.js
> +        this.props.filterPast();
make endpoint that will return past of future items instead of fetch all data and filter them

2017-08-11 19:38 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/components/ListWithTripsItems.js
> +                        <input type="button" className="btn btn-secondary tab-button" value="Past trips" onClick={this.props.filterPast} />
use A or BUTTON tags

2017-08-11 19:38 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/components/ListWithTripsItems.js
> +                    <TripsListItem  key={index} tripData={tripData}/>
move this to separate component

2017-08-11 19:38 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/components/ListWithTripsItems.js
> +                        <input type="button" className="btn btn-secondary tab-button" value="Upcoming trips" onClick={this.props.filterUpcoming} />
use navigation to show future of past items

2017-08-11 19:38 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/components/modal.js
> +class Modal extends Component {
use bootstrap style and markup

2017-08-11 19:38 UTC, TatsuUkraine commented on app/Http/Controllers/Api/Driver/TripListController.php
> +            $result = $this->service->getUserTrips($userId);
use get params to specify past or future items filter or all if filter params not passed

2017-08-11 19:38 UTC, TatsuUkraine commented on app/Services/TripsListService.php
> +    public function getUserTrips(int $userId){
codestyle

2017-08-11 19:50 UTC, TatsuUkraine commented
as for Modal solution, you can take a look how Modal was in use here https://github.com/BinaryStudioAcademy/bsa-2017-bebeep/pull/16

2017-08-11 19:51 UTC, TatsuUkraine commented
@mivashchuk merge development branch into your to resolve conflicts

2017-08-12 06:48 UTC, sergey-ben requested changes
По части backend есть одна проблема, но она весьма весомая :-) 
Имеется TripsListService
Так же имеется TripsManager 
Один из этих сервисов явно лишний :-) К тому же Service Layer не должен знать о существовании БД, он не должен уметь работать с БД. Он должен знать только о репозитории и работать с репозиторием

2017-08-13 13:15 UTC, TatsuUkraine requested changes

2017-08-13 13:15 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/actions.js
> +        axios.get(url+'?filter=past')
use RequestService to make request to server

2017-08-13 13:15 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/actions.js
> +        axios.get(url+'?filter=upcoming')
use RequestService to make request to server

2017-08-13 13:15 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/actions.js
> +export function filterPast() {
actions should reflects logic that they performs in this case it's FETCH_PAST

2017-08-13 13:15 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/actions.js
> +export function filterUpcoming() {
actions should reflects logic that they performs in this case it's FETCH_UPCOMING

2017-08-13 13:15 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/components/MapModal.js
> +class MapModal extends Component {
use already define Modal component, take a look at how reset password modal is made

2017-08-13 13:15 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/components/TripsListItem.js
> +        this.showModal = this.showModal.bind(this);
don't use global state for modal show/hide, reuse already implemented Modal component that uses local state

2017-08-13 13:15 UTC, TatsuUkraine commented on resources/assets/js/features/tripsList/layouts/TripsList.js
> +                <MapModal/>
you can move MapModal into List component and define open/close modal there instead of global state usage

2017-08-14 11:11 UTC, sergey-ben requested changes

2017-08-14 11:11 UTC, sergey-ben commented on app/Http/Controllers/Api/Driver/TripListController.php
> +            $result = $this->service->getUserTrips($userId);
or you can create endpoints like these
`/api/v1/trips`
`/api/v1/trips/upcoming`
`/api/v1/trips/past`

2017-08-14 11:11 UTC, sergey-ben commented on app/Http/Controllers/Api/Driver/TripListController.php
> +        }catch (UserNotHaveTrips $e){
you don't have to catch this exception. You don't throw this exception anywhere. 
Use different action for past/upcoming/all trips
pass request interface into the service layer. 
use authenticated user

2017-08-14 11:11 UTC, sergey-ben commented on app/Repositories/TripRepository.php
> +        $pastTrips = Trip::where('trips.user_id','=',$userId)->
codestyle issue

2017-08-14 11:11 UTC, sergey-ben commented on app/Services/TripsListService.php
> +      $allUserTrips = $this->repository->getAllTrips($userId);
there should be 4 spaces instead of 2

2017-08-14 11:11 UTC, sergey-ben commented on app/Repositories/TripRepository.php
> +        whereDate('start_at', '<=',new \DateTime())->
use end date instead. Don't forget that trip will have multiple routes.

2017-08-15 17:45 UTC, closed without merging