Feature/broadcast notifications
BinaryStudioAcademy/bsa-2017-bebeep pull request #150
Opened 2017-09-11 07:54 UTC by lenchv

2017-09-11 17:37 UTC, TatsuUkraine requested changes

2017-09-11 17:37 UTC, TatsuUkraine commented on resources/assets/js/app/services/BroadcastService.js
> +const PUSHER_KEY = '93ab4ad70ab16afc1f6d';
create config file where you will define such api keys

2017-09-11 17:37 UTC, TatsuUkraine commented on resources/assets/js/app/services/AuthService.js
> +        return -1;
return null

2017-09-11 17:37 UTC, TatsuUkraine commented on resources/assets/js/app/services/NotificationService.js
> +        case "booking_approved":
define notification types as const

2017-09-11 17:37 UTC, TatsuUkraine commented on resources/assets/js/app/components/Notifications.js
> +            this.setState({
move this state set to separate method

2017-09-11 17:37 UTC, TatsuUkraine commented on resources/assets/js/app/components/Notifications.js
> +                    browserHistory.push('/dashboard/notifications')
base on notification type navigate use to appropriate page like trip or booking page and mark this notification as read. For cases when page can't be opened - navigate to notification page

2017-09-11 19:09 UTC, sergey-ben submitted a review, later dismissed

2017-09-12 07:03 UTC, TatsuUkraine approved these changes

2017-09-12 07:14 UTC, merged