Feature/reset password
BinaryStudioAcademy/bsa-2017-bebeep pull request #16
Opened 2017-08-11 19:27 UTC by lenchv

2017-08-11 19:49 UTC, TatsuUkraine requested changes

2017-08-11 19:49 UTC, TatsuUkraine commented on resources/assets/js/app/services/RequestService.js
> +    if (typeof axios[method] === 'function') {
call makeRequest instead of axios

2017-08-12 06:39 UTC, sergey-ben requested changes
написал в личку )

2017-08-12 18:43 UTC, sergey-ben approved these changes

2017-08-12 18:43 UTC, merged