Feature/user subscriptions
BinaryStudioAcademy/bsa-2017-bebeep pull request #162
Opened 2017-09-12 22:39 UTC by komax93

Задание выполнено на 95%, промежуточный ПР.
Требуются уточнения.

2017-09-13 15:48 UTC, sergey-ben submitted a review, later dismissed

2017-09-13 17:36 UTC, TatsuUkraine requested changes

2017-09-13 17:36 UTC, TatsuUkraine commented on resources/assets/js/features/search/components/Result/_Modals/SubscribeModal.js
> +        let userId = (userObj.user.sub) ? userObj.user.sub : null;
don't use "sub" key, there's method getUserId that will return userId or null

2017-09-13 17:36 UTC, TatsuUkraine commented on resources/assets/js/features/search/components/Result/_Modals/SubscribeModal.js
> +import { getAuthUser } from 'app/services/AuthService';
I'm not sure that AuthService has method getAuthUser

2017-09-13 17:36 UTC, TatsuUkraine commented on resources/assets/js/features/search/components/Result/_Modals/SubscribeModal.js
> +                    this.setState({confirmLoginModalIsOpen: true});
open login modal before you will try to send subscribe request

2017-09-13 17:42 UTC, TatsuUkraine commented
@komax93 resolve conflicts

2017-09-13 18:57 UTC, komax93 commented on resources/assets/js/features/search/components/Result/_Modals/SubscribeModal.js
> +                    this.setState({confirmLoginModalIsOpen: true});
@TatsuUkraine В данном случае, это необходимо, для того, что бы показывать модалку перехода на login page, только в случае того, когда email пользователя есть в базе данных таблицы users. Если пользователь обнаружен, кидается исключение с 403 ответом сервера и тогда всплывает модальное окно с предложением перейти на login page. Иначе он может изменить email и будет успешно подписан. Данные действия выполняются только для не авторизованых пользователей.

2017-09-13 19:14 UTC, TatsuUkraine commented on resources/assets/js/features/search/components/Result/_Modals/SubscribeModal.js
> +                    this.setState({confirmLoginModalIsOpen: true});
@komax93 ну 403 это ошибка доступа, но к ресурсу ведь доступ есть, т.е в данном случае это больше относится к ошибке валидации, завтра обсудим если что

2017-09-13 21:38 UTC, komax93 commented on resources/assets/js/features/search/components/Result/_Modals/SubscribeModal.js
> +                    this.setState({confirmLoginModalIsOpen: true});
@TatsuUkraine Готово. Теперь 403 ошибка не возвращается. Валидация происходит по response message, объекту с ключом "error".

Все конфликты исправил. 

StyleCi пофиксил.

2017-09-14 15:00 UTC, TatsuUkraine approved these changes

2017-09-14 15:00 UTC, merged