Feature/search users
BinaryStudioAcademy/bsa-2017-bebeep pull request #199
Opened 2017-09-15 19:10 UTC by lenchv

2017-09-17 08:04 UTC, ruig1992 commented
**TODO** :: Typeahead search and go to `/dashboard/messages/:user_id` when clicking in the typeahead search results.

2017-09-17 12:35 UTC, TatsuUkraine requested changes

2017-09-17 12:35 UTC, TatsuUkraine commented on resources/assets/js/features/chat/components/SearchUsers.js
> +        /*<div className="input-group-addon search-users__icon-wrapper">
no need commented code in new component

2017-09-17 12:35 UTC, TatsuUkraine commented on resources/assets/js/features/chat/components/SearchUsers.js
> +                    style={{
avoid using inline styles

2017-09-17 12:38 UTC, ruig1992 commented
@TatsuUkraine   This PR is not yet ready for review. But, thanks for your remarks! :-)

2017-09-18 06:16 UTC, sergey-ben approved these changes

2017-09-18 07:22 UTC, TatsuUkraine approved these changes

2017-09-18 07:22 UTC, merged