Feature/fix responsive in chat page
BinaryStudioAcademy/bsa-2017-bebeep pull request #215
Opened 2017-09-17 10:23 UTC by kaharlykskyi

2017-09-17 12:32 UTC, TatsuUkraine requested changes

2017-09-17 12:32 UTC, TatsuUkraine commented on resources/assets/js/features/chat/components/MessagingPage/MessagingContainer.js
> +            DRIVER_PERMISSIONS = 2,
UserService already has permissions, also AuthService has method checkPermissions

2017-09-17 14:07 UTC, TatsuUkraine requested changes

2017-09-17 14:07 UTC, TatsuUkraine commented on resources/assets/js/features/chat/components/MessagingPage/MessagingContainer.js
> +        if (user.permissions === USER_ROLE_DRIVER) {
use AuthService.checkPermission if this method fits here

2017-09-17 16:49 UTC, kaharlykskyi commented on resources/assets/js/features/chat/components/MessagingPage/MessagingContainer.js
> +        if (user.permissions === USER_ROLE_DRIVER) {
окей, но я что то не могу понять, как он работает. что за identically?
```
checkPermissions(permissions, identically) {
            const sessionPermissions = getFromState('permissions');

            if (!permissions) {
                return true;
            }

            return identically
                ? permissions === sessionPermissions
                : !!(permissions & sessionPermissions);
}
```

2017-09-18 08:46 UTC, ruig1992 commented on resources/assets/js/features/chat/components/MessagingPage/MessagingContainer.js
> +        if (user.permissions === USER_ROLE_DRIVER) {
@TatsuUkraine  @kaharlykskyi
`AuthService.checkPermission`  проверяет права для *текущего залогиненного* пользователя. Поэтому в данном случае нужно использовать методы `checkDriverRole` и `checkPassengerRole` от `app/services/UserService`.  В эти методы нужно передать `user.permissions` для проверки.

```
import {
    USER_ROLE_DRIVER,
    USER_ROLE_PASSENGER,
    checkDriverRole,
    checkPassengerRole
} from 'app/services/UserService';

...

let link = '';

if (checkDriverRole(user.permissions)) {
    link = `/driver/${user.id}`;
} else if (checkPassengerRole(user.permissions)) {
    link = `/passenger/${user.id}`;
}
```

2017-09-18 08:57 UTC, ruig1992 commented on resources/assets/js/features/chat/components/MessagingPage/MessagingContainer.js
> +        if (user.permissions === USER_ROLE_DRIVER) {
@kaharlykskyi  По поводу **проверки на идентичность прав** (*identically*) - в Slack.)

2017-09-18 10:09 UTC, kaharlykskyi commented on resources/assets/js/features/chat/components/MessagingPage/MessagingContainer.js
> +        if (user.permissions === USER_ROLE_DRIVER) {
@ruig1992 спасибо, вчера уже разобрались))

2017-09-18 19:16 UTC, TatsuUkraine approved these changes

2017-09-19 06:45 UTC, merged