Feature/currency  search page and trip details  new
BinaryStudioAcademy/bsa-2017-bebeep pull request #248
Opened 2017-09-21 15:25 UTC by ruig1992

[![trs](https://user-images.githubusercontent.com/12577743/30219063-9438ad58-94c3-11e7-8359-212ee6e46cea.png) Currency: search page and trip details](https://trello.com/c/hnH3zvBe)

2017-09-21 18:03 UTC, TatsuUkraine requested changes

2017-09-21 18:03 UTC, TatsuUkraine commented on resources/assets/js/features/search/components/Result/Result.js
> +        CurrencyService.convertValue(this.state.meta.priceRange[0], currency);
it seems that those 2 rows do nothing here

2017-09-22 06:23 UTC, ruig1992 commented
**The last thing to do** is change the displayed price values in the filter when the user changes the currency in the currency dropdown list.

2017-09-22 07:20 UTC, sergey-ben approved these changes

2017-09-22 07:24 UTC, merged