Feature/js build config starter tmpl
BinaryStudioAcademy/bsa-2017-bebeep pull request #4
Opened 2017-08-07 19:06 UTC by ruig1992

Added js config build for React components and the Starter boilerplate for viewing and testing of the build results.

2017-08-08 05:56 UTC, ruig1992 commented
Сейчас еще обновлю routes/web.php маршруты, чтобы все запросы шли на index

2017-08-08 17:30 UTC, sergey-ben commented
![](https://github.trello.services/images/mini-trello-icon.png) [JS build config and Starter boilerplate](https://trello.com/c/9fYeciIW/17-js-build-config-and-starter-boilerplate)

2017-08-08 19:15 UTC, TatsuUkraine requested changes

2017-08-08 19:15 UTC, TatsuUkraine commented on resources/views/index.blade.php
> +    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap.native/2.0.12/bootstrap-native-v4.min.js"></script>
use npm to install bootstrap package and use import inside app instead of <script> tag

2017-08-08 19:15 UTC, TatsuUkraine commented on resources/assets/js/features/vehicle/actionTypes.js
> +export const GET_VEHICLES = 'GET_VEHICLES';
rename action type to format {componentName}_{action}, for example VEHICLE_GET_ALL VEHICLE_GET VEHICLE_ADD and etc.

2017-08-08 19:15 UTC, TatsuUkraine commented on resources/assets/js/app/routes.js
> +import VehicleOne from '../features/vehicle/views/VehicleOne';
rename VehicleOne to VehicleDetails

2017-08-08 19:17 UTC, TatsuUkraine commented
@ruig1992 rename folder app/views to app/components

2017-08-08 20:55 UTC, TatsuUkraine requested changes

2017-08-08 20:55 UTC, TatsuUkraine commented on .gitignore
> -/public/js
both lines should be in gitignore to avoid conflict problems

2017-08-09 06:50 UTC, TatsuUkraine approved these changes

2017-08-09 06:50 UTC, merged