Trip stopovers
BinaryStudioAcademy/bsa-2017-bebeep pull request #58
Opened 2017-08-19 19:05 UTC by Rhincodon

2017-08-19 22:23 UTC, TatsuUkraine requested changes

2017-08-19 22:23 UTC, TatsuUkraine commented on resources/assets/js/app/components/DirectionsMap.js
> +                let route = result.routes[0];
create class that will accept on construct "result" var and will have getters for all needed properties like - getRoute, getRouteStartPoint, getRouteEndPoint, getDuration etc.

2017-08-19 22:23 UTC, TatsuUkraine commented on resources/assets/js/features/trip/components/Containers/EditTripContainer.js
> +                }, 10);
if you want to execute some method in other scope, 0 will be enough, otherwise - it could make bad joke with you

2017-08-19 22:23 UTC, TatsuUkraine commented on resources/assets/js/features/trip/components/Forms/TripForm.js
> +            waypointsView = this.props.waypoints.map((point, index) =>
move this to separate components

2017-08-20 10:31 UTC, sergey-ben approved these changes

2017-08-20 10:31 UTC, sergey-ben commented on app/Services/TripsService.php
> +    public static function getRoutesFromWaypoints($startPoint, $endPoint, $waypoints)
it's better not to use static methods in services. It breaks DI principles

2017-08-20 10:33 UTC, sergey-ben commented
@TatsuUkraine all your remarks were fixed

2017-08-20 10:33 UTC, merged