Feature/trip wizard
BinaryStudioAcademy/bsa-2017-bebeep pull request #96
Opened 2017-08-29 15:26 UTC by lenchv

2017-08-29 17:58 UTC, sergey-ben submitted a review, later dismissed

2017-08-29 19:23 UTC, TatsuUkraine requested changes

2017-08-29 19:23 UTC, TatsuUkraine commented on resources/assets/js/app/components/Controls/InputPlaces.js
> +                    className={'form-input ' + (ico || '') + (address !== '' || focused ? ' form-input_focus' : '')}
if you need style on focus you can use pseudo selector :focus , no need to create listeners and separate style

same for empty input, it can be done with placeholder defined and :placeholder-shown pseudo selector

2017-08-29 19:23 UTC, TatsuUkraine commented on resources/assets/js/features/user/components/Register/Form.js
> +                            savePendingTrip(tripPending).then(() => completeTrip());
no need hasTripPending here you can define should you create trip or not based on global state tripPending, if you have one - save, if not - don't

2017-08-29 19:23 UTC, TatsuUkraine commented on resources/assets/js/features/wizard-trip/reducer.js
> +    step: INIT,
all props that describes selected data should be separated from rest props, put them in data or pendingTrip or tripToSave property

2017-08-29 19:23 UTC, TatsuUkraine commented on resources/assets/js/app/services/WizardTripService.js
> +                browserHistory.push('/trips');
at this step method that provides save shouldn't know about where user should be redirected

2017-08-29 19:23 UTC, TatsuUkraine commented on resources/assets/js/features/wizard-trip/components/StepTwo.js
> +            price = value && !isNaN(+value[0]) ? +value[0] : (value && value.length !== 0 ? this.state.price : '');
move such checks to helper or service

2017-08-29 19:23 UTC, TatsuUkraine commented on resources/assets/js/features/wizard-trip/components/StepTwo.js
> +            seats = value && !isNaN(value) && value > 0 ? value : (value <= 0 ? '' : this.state.seats);
move such checks to helper or service

2017-08-29 19:23 UTC, TatsuUkraine commented on resources/assets/js/features/wizard-trip/styles/wizard-trip.scss
> +    &_active {
"active" it's modifier so it should have -- separator instead of _

2017-08-30 09:43 UTC, TatsuUkraine approved these changes

2017-08-30 09:46 UTC, merged